#server -> default 8080
server:
  port: 8080

# database link
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: lhe
    password: 1234

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

# debug
logging:
  level:
    root: debug
    org.mybatis: debug
    org.springframework.web: debug
#    org.springframework.jdbc: debug